config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root 'home#index'
  get 'home', to: 'home#index', as: 'home'
  resources :users
  resources :movies do
    collection do
      get 'search', to: 'movies#search'
    end
    post 'store', on: :collection
    get 'details', on: :collection
  end

  resources :sessions, only: %i[new create destroy]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :ratings, only: [:create]
  resources :favorites, only: %i[create destroy]

  get 'rated_movies', to: 'movies#rated_movies'

  resources :comments, only: %i[index create edit update destroy]

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/controllers/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  API_KEY = ENV['API_KEY']
  AUTH_TOKEN = ENV['TOKEN']
  def index
    return unless logged_in?

    favorites_page = params[:favorites_page] || 1
    rated_page     = params[:rated_page]     || 1
    watched_page   = params[:watched_page]   || 1

    I18n.locale = params[:locale] || extract_locale_from_referer || :en
    language = current_language_code

    favorites = current_user.favorite_movies.order(created_at: :desc)
    user_ratings = current_user.ratings.order(created_at: :desc)
    watched = current_user.watched_movies.order(created_at: :desc)

    @comments = current_user.comments.order(created_at: :desc)

    @cached_movies = CachedMovie.where(movie_id: @comments.map(&:movie_id), language: language).index_by(&:movie_id)

    favorite_ids = favorites.pluck(:movie_id)
    rating_ids = user_ratings.pluck(:movie_id)

    favoritemovies = favorites.map do |favoritemovie|
      cached = CachedMovie.find_by(movie_id: favoritemovie.movie_id, language: language)
      next unless cached

      tmdb_rating_5 = cached.vote_average.to_f / 2.0
      tmdb_votes = begin
        cached.vote_count.to_i
      rescue StandardError
        0
      end

      user_avg = Rating.where(movie_id: favoritemovie.movie_id).average(:score) || 0
      user_count = Rating.where(movie_id: favoritemovie.movie_id).count
      rating = Rating.find_by(user_id: current_user.id, movie_id: favoritemovie.movie_id)
      total_votes = tmdb_votes + user_count

      combined = total_votes.positive? ? ((tmdb_rating_5 * tmdb_votes + user_avg * user_count) / total_votes) : tmdb_rating_5
      {
        'id' => favoritemovie.movie_id,
        'title' => cached.title,
        'overview' => cached.overview,
        'poster_path' => cached.poster_path,
        'backdrop_path' => cached.backdrop_path,
        'user_score' => rating&.score || nil,
        'vote_average' => cached.vote_average.to_f,
        'vote_count' => tmdb_votes,
        'rating' => combined.round(2),
        'total_votes' => total_votes
      }
    end.compact

    all_rated = user_ratings.reject { |rating| favorite_ids.include?(rating.movie_id) }.map do |rating|
      movie_id = rating.movie_id

      cached = CachedMovie.find_by(movie_id: movie_id, language: language)
      next unless cached

      tmdb_rating_5 = cached.vote_average.to_f / 2.0
      tmdb_votes = begin
        cached.vote_count.to_i
      rescue StandardError
        0
      end

      user_avg = Rating.where(movie_id: movie_id).average(:score) || 0
      user_count = Rating.where(movie_id: movie_id).count
      total_votes = tmdb_votes + user_count

      combined = total_votes.positive? ? ((tmdb_rating_5 * tmdb_votes + user_avg * user_count) / total_votes) : tmdb_rating_5

      {
        'id' => movie_id,
        'title' => cached.title,
        'overview' => cached.overview,
        'poster_path' => cached.poster_path,
        'backdrop_path' => cached.backdrop_path,
        'user_score' => rating.score,
        'vote_average' => cached.vote_average.to_f,
        'vote_count' => tmdb_votes,
        'rating' => combined.round(2),
        'total_votes' => total_votes
      }
    end.compact

    watchedmovies = watched.reject { |watchedmovie| rating_ids.include?(watchedmovie.movie_id) }.map do |watchedmovie|
      cached = CachedMovie.find_by(movie_id: watchedmovie.movie_id, language: language)
      next unless cached

      tmdb_rating_5 = cached.vote_average.to_f / 2.0
      tmdb_votes = begin
        cached.vote_count.to_i
      rescue StandardError
        0
      end

      user_avg = Rating.where(movie_id: watchedmovie.movie_id).average(:score) || 0
      user_count = Rating.where(movie_id: watchedmovie.movie_id).count
      total_votes = tmdb_votes + user_count

      combined = total_votes.positive? ? ((tmdb_rating_5 * tmdb_votes + user_avg * user_count) / total_votes) : tmdb_rating_5

      {
        'id' => watchedmovie.movie_id,
        'title' => cached.title,
        'overview' => cached.overview,
        'poster_path' => cached.poster_path,
        'backdrop_path' => cached.backdrop_path,
        'vote_average' => cached.vote_average.to_f,
        'vote_count' => tmdb_votes,
        'rating' => combined.round(2),
        'total_votes' => total_votes
      }
    end.compact

    @favorite_movies = Kaminari.paginate_array(favoritemovies).page(favorites_page).per(10)
    @rated_movies = Kaminari.paginate_array(all_rated).page(rated_page).per(10)
    @watched_movies = Kaminari.paginate_array(watchedmovies).page(watched_page).per(10)

    @movies = []

    if @favorite_movies.empty? && @rated_movies.empty? && @watched_movies.empty?
      language = current_language_code

      api_url = "https://api.themoviedb.org/3/movie/popular?api_key=#{API_KEY}&language=#{language}&page=1"
      response = HTTParty.get(api_url, headers: { 'Authorization' => "Bearer #{AUTH_TOKEN}" })

      if response.success?
        rawmovies = response.parsed_response['results']

        rawmovies.each do |movie|
          tmdb_rating_5 = movie['vote_average'].to_f / 2.0
          tmdb_votes = begin
            movie['vote_count'].to_i
          rescue StandardError
            0
          end

          user_ratings = Rating.where(movie_id: movie['id'])
          user_avg = user_ratings.average(:score) || 0
          user_count = user_ratings.count

          total_votes = tmdb_votes + user_count

          combined = if total_votes.positive?
                       ((tmdb_rating_5 * tmdb_votes) + (user_avg * user_count)) / total_votes
                     else
                       tmdb_rating_5
                     end

          movie['rating'] = combined.round(2)
          movie['total_votes'] = total_votes
        end
        @movies = rawmovies
      end
    else
      respond_to do |format|
        format.html
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace('favorite_movies', partial: 'home/favorite_movies',
                                                    locals: { favorite_movies: @favorite_movies }),
            turbo_stream.replace('rated_movies', partial: 'home/rated_movies', locals: { rated_movies: @rated_movies }),
            turbo_stream.replace('watched_movies', partial: 'home/watched_movies',
                                                   locals: { watched_movies: @watched_movies })
          ]
        end
      end
    end
  end

  def extract_locale_from_referer
    URI.parse(request.referer || '').query
       &.split('&')
       &.map { |p| p.split('=') }
       &.to_h&.[]('locale')
       &.to_sym
  rescue StandardError
    nil
  end

  private

  def current_language_code
    case I18n.locale
    when :es then 'es-MX'
    when :en then 'en-US'
    when :ko then 'ko-KR'
    when :zh then 'zh-CN'
    else 'en-US'
    end
  end
end

app/views/home/_favorite_movies.html.erb
<turbo-frame id="favorite_movies_frame">
  <%= render partial: "movie", collection: favorite_movies, as: :movie %>

  <%= paginate @favorite_movies, param_name: :favorites_page %>
</turbo-frame>

app/views/home/_movie.html.erb
<% if movie['backdrop_path'].present? %>
  <div class="movie" style="--background-image: url('https://image.tmdb.org/t/p/w1280<%= movie['backdrop_path'] %>');">
<% else %>
  <div class="movie no-background">
<% end %>
  <div class="movie-left">
    <% user_rating = current_user&.ratings&.find_by(movie_id: movie['id'])&.score || 0 %>
    <% favorite = current_user&.favorite_movies&.find_by(movie_id: movie['id']) || false %>
    <div class="poster-wrapper" data-movie-id="<%= movie["id"] %>" vote-count="<%= movie['vote_count'] %>" vote-average="<%= movie['vote_average'] %>" ratings-text="<%= t('ratings') %>" title="<%= movie['title'] %>" overview="<%= movie['overview'] %>" poster_path="<%= movie['poster_path'] %>" backdrop_path="<% movie['backdrop_path'] %>">
      <%= form_tag store_movies_path, method: :post, data: { turbo: false } do %>
      <%= hidden_field_tag 'movie[id]', movie['id'] %>
      <%= hidden_field_tag 'movie[title]', movie['title'] %>
      <%= hidden_field_tag 'movie[overview]', movie['overview'] %>
      <%= hidden_field_tag 'movie[poster_path]', movie['poster_path'] %>
      <%= hidden_field_tag 'movie[backdrop_path]', movie['backdrop_path'] %>
      <%= hidden_field_tag 'movie[vote_average]', movie['vote_average'] %>
      <%= hidden_field_tag 'movie[vote_count]', movie['vote_count'] %>
      <%= hidden_field_tag 'movie[rating]', movie['rating'] %>
      <%= hidden_field_tag 'movie[total_votes]', movie['total_votes'] %>

      <%= button_tag type: 'submit', style: "background:none; border:none; padding:0;" do %>
        <%= image_tag(
          movie['poster_path'] ? "https://image.tmdb.org/t/p/w500#{movie['poster_path']}" : asset_path('placeholder.png'),
          class: "movie-poster"
        ) %>
      <% end %>
      <%= button_tag(favorite ? '💛' : '❤️', class: "poster-button", type: 'button') %>
      <% end %>
    </div>
  </div>
  <div class="movie-info">
    <div class="movie-details">
      <strong class="movie-title"><%= movie['title'] %></strong><br>
      <p class="movie-overview"><%= movie['overview'] != "" ? movie['overview'] : t("no_synopsis_available") %></p><br>
    </div>
    <div class="movie-rating" data-movie-id="<%= movie["id"] %>" vote-count="<%= movie['vote_count'] %>" vote-average="<%= movie['vote_average'] %>" ratings-text="<%= t('ratings') %>" title="<%= movie['title'] %>" overview="<%= movie['overview'] %>" poster_path="<%= movie['poster_path'] %>" backdrop_path="<% movie['backdrop_path'] %>">
      <% rating = (movie['rating'] || 0).to_f %>
      <% 1.upto(5) do |i| %>
      <% star_class = 
        if rating >= i
          "fa-solid"
        elsif rating >= i - 0.5
          "fa-solid fa-star-half-stroke"
        else
          "fa-regular"
        end
      %>
      <% star_color = (user_rating >= i - 0.5) ? "color: #ffae10" : "" %>
        <i class="fa-star <%= star_class %> star" style="<%= star_color %>" data-score="<%= i %>"></i>
      <% end %>
      <span class="rating-score">
        <span>
          <%= number_with_precision(rating, precision: 1) %> / 5
        </span>
        <br>
        <span>
          (<%= movie['total_votes'] %> <%= t("ratings") %>)
        </span>
      </span>
    </div>
  </div>
</div>

app/views/home/_rated_movies.html.erb
<turbo-frame id="rated_movies_frame">
  <%= render partial: "movie", collection: rated_movies, as: :movie %>

  <%= paginate rated_movies, param_name: :rated_page %>
</turbo-frame>

app/views/home/_watched_movies.html.erb
<turbo-frame id="watched_movies_frame">
  <%= render partial: "movie", collection: watched_movies, as: :movie %>

  <%= paginate watched_movies, param_name: :watched_page %>
</turbo-frame>

app/views/home/index.html.erb
<!-- app/views/home/index.html.erb --> <!-- Página principal -->
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag :movies, "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag :comments, "data-turbo-track": "reload" %>
<% end %>

<% if logged_in? %>
  <h2><%= t("welcome") %>, <%= current_user.username %></h2>
<% else %>
  <h2><%= t("welcome") %></h2>
<% end %>

<% if logged_in? %> <!-- Si el usuario está logeado -->
  <% if @favorite_movies.present? %>
    <h3><%= t("users.favoritemovies") %></h3>
    <div id="favorite_movies">
      <%= render 'home/favorite_movies', favorite_movies: @favorite_movies %>
    </div>
  <% end %>

  <% if @rated_movies.present? %>
    <h3><%= t("users.ratedmovies") %></h3>
    <div id="rated_movies">
      <%= render 'home/rated_movies', rated_movies: @rated_movies %>
    </div>
  <% end %>
  
  <% if @watched_movies.present? %>
    <h3><%= t("movies.watched") %></h3>
    <div id="watched_movies">
      <%= render 'home/watched_movies', watched_movies: @watched_movies %>
    </div>
  <% end %>

  <% if !@favorite_movies.present? && !@rated_movies.present? && !@watched_movies.present? %>
    <% if @movies.any? %>
      <div id="movies-container">
      <% @movies.each do |movie| %>
        <%= render 'movies/movie', movie: movie %>
      <% end %>
      </div>
    <% else %>
      <p><%= t("movies.nomovies") %></p>
    <% end %>
  <% end %>

  <% if @comments.any? %>
    <div class="comments-list">
      <%= render partial: "comments/home_comment", collection: @comments, as: :comment, locals: { movie: @movie } %>
    </div>
  <% else %>
  <div class="comment-item">
    <p><%= t("users.no_comments") %></p>
  </div>
  <% end %>
<% else %>
  <div class="home">
    <br>
    <%= link_to t("login.title"), login_path %>
    <%= link_to t("login.register"), new_user_path%>
  </div>
<% end %>

<script>
  document.addEventListener("turbo:frame-load", function(event) {
    window.scrollTo({ top: 0, behavior: "smooth" });
  });
</script>

<%= javascript_include_tag "movies", "data-turbo-track": "reload", defer: true %>