config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root 'home#index'
  get 'home', to: 'home#index', as: 'home'
  resources :users
  resources :movies do
    collection do
      get 'search', to: 'movies#search'
    end
    post 'store', on: :collection
    get 'details', on: :collection
  end

  resources :sessions, only: %i[new create destroy]
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :ratings, only: [:create]
  resources :favorites, only: %i[create destroy]

  get 'rated_movies', to: 'movies#rated_movies'

  resources :comments, only: %i[index create edit update destroy]

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= content_for(:title) || "Cinemarx" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %> <!-- Insertar head de la vista -->

    <%= stylesheet_link_tag :application, "data-turbo-track": "reload" %>

    <%= yield :stylesheets %>
    <link href='https://fonts.googleapis.com/css?family=Noto Serif' rel='stylesheet'> <!-- Fuente Noto Serif -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"> <!-- Usar font awesome para las estrellas -->
    <%= javascript_importmap_tags %>
</head>
<body>
    <header>
        <%= link_to home_path, data: { turbo: false } do %>
            <h1 id="title">Cine<span style="color: #ff0040;">marx</span></h1>
        <% end %>
        <nav>
            <%= link_to t("populars"), movies_path, data: { turbo: false }, class: "header-links" %>
            <% if !logged_in? %>
                <%= link_to t("login.title"), login_path, class: "header-links" %>
                <%= link_to t("login.register"), new_user_path, class: "header-links" %>
            <% elsif logged_in? %>
            <%= link_to t("login.logout"), logout_path, class: "header-links confirm", data: { controller: "confirm", action: "confirm#confirm"} %>
            <% end %>
            <% if admin? %>
              <%= link_to t("users.list"), users_path, class: "header-links" %>
              <%= link_to t("users.create"), new_user_path, class: "header-links" %>
            <% end %>
        </nav>
  
        <div class="search-box">
          <%= form_with url: search_movies_path, method: :get, local: true do %>
            <button type="submit" class="search-button">
              <img src="<%= asset_path('search.png') %>" alt="search" id="search-button">
            </button>
            <input type="text" name="query" placeholder="<%= t('search') %>" id="search">
          <% end %>
        </div>

        <%= form_with url: request.path, method: :get, local: true, html: { id: "language-dropdown" } do %>
        <% params.to_unsafe_h.except(:locale, :controller, :action).each do |key, value| %>
          <% if value.is_a?(Array) %>
            <% value.each do |v| %>
              <%= hidden_field_tag key, v %>
            <% end %>
          <% else %>
            <%= hidden_field_tag key, value %>
          <% end %>
        <% end %>

        <%= select_tag :locale, options_for_select([["English", "en"], ["Español", "es"], ["한국어", "ko"], ["中文", "zh"]], I18n.locale), onchange: "this.form.submit();" %>
      <% end %>
    </header>
    
    <div class="fondo" style="--bg-url: url(<%= asset_path('background.jpg') %>)">
    <% if flash[:notice] %> <!-- Mostrar errores y alertas en todas las páginas -->
      <p class="notice"><%= flash[:notice] %></p>
    <% elsif flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>
    <%= yield %> <!-- Insertar body de la vista -->
    
    <script>
      document.addEventListener("turbo:load", () => { // Al cargar la página
        document.querySelectorAll(".confirm:not([data-confirm-processed])").forEach(element => { // Todos los elementos de clase confirm
          element.dataset.confirmProcessed = "true";

          element.addEventListener("click", event => {
            if (!confirm("<%= j t("confirmation") %>")) { // Mostrar confirmación traducida
              event.preventDefault();
            }
          });
        });
      });
    </script>
</body>
</html>